import type { Metadata } from "next";
import { Poppins, Nunito } from "next/font/google";
// @ts-ignore
import "@/app/globals.css";
import AuthInitializer from "@/components/AuthInitializer";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable: "--font-sans",
  weight: ["400", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

const nunito = Nunito({
  variable: "--font-mono",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "KrishiVed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${nunito.variable} antialiased`}>
        <AuthInitializer />
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
